FROM python:3.12-alpine

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app/

COPY Pipfile Pipfile.lock /app/

RUN pip install pipenv --upgrade

RUN pipenv install --system

# CMD ["uvicorn", "--host", "0.0.0.0", "app.main:app", "--reload"]