version: "3"

services:

  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn --host 0.0.0.0 app.main:app --reload
      "
  
  
  db:
    image: postgres:17.2-alpine3.21
    
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

    volumes:
      - "db_data:/var/lib/postgresql/data"
    

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: